apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  config.yaml: |
    # note: all of these values are bogus; the broker will start up but not actually work
    inbound:
      wireguard:
        localAddress: 192.168.0.2
        privateKey: 8DzUuki1Qn+Fdoc8IuRfhCfEL6/OMAIknx45QGtJFVs=
        peers:
        - publicKey: OgJxJJvNIFZb5UO15VACP9IlVnhkURq+v7PV80c0IB0=
          endpoint: example.com:51820
          allowedIps: 192.168.0.1/32
      heartbeat:
        url: http://192.168.0.1/ping
      allowlist:
        - url: http://example.com/*
          methods:
          - GET
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: semgrep-network-broker
  name: semgrep-network-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semgrep-network-broker
  template:
    metadata:
      labels:
        app: semgrep-network-broker
    spec:
      containers:
      - name: gateway
        image: image-goes-here
        args:
        - -c
        - /conf/config.yaml
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /conf
          name: config-volume
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: broker-config