name: test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make deps test
